package com.android.systemui;

import android.app.AlarmManager;
import android.app.INotificationManager;
import android.app.IWallpaperManager;
import android.hardware.SensorPrivacyManager;
import android.hardware.display.NightDisplayListener;
import android.os.Handler;
import android.os.Looper;
import android.util.ArrayMap;
import android.util.DisplayMetrics;
import android.view.IWindowManager;
import com.android.internal.annotations.VisibleForTesting;
import com.android.internal.logging.MetricsLogger;
import com.android.internal.logging.UiEventLogger;
import com.android.internal.statusbar.IStatusBarService;
import com.android.internal.util.Preconditions;
import com.android.keyguard.KeyguardSecurityModel;
import com.android.keyguard.KeyguardUpdateMonitor;
import com.android.keyguard.clock.ClockManager;
import com.android.settingslib.bluetooth.LocalBluetoothManager;
import com.android.systemui.accessibility.AccessibilityButtonModeObserver;
import com.android.systemui.accessibility.AccessibilityButtonTargetsObserver;
import com.android.systemui.accessibility.floatingmenu.AccessibilityFloatingMenuController;
import com.android.systemui.appops.AppOpsController;
import com.android.systemui.assist.AssistManager;
import com.android.systemui.broadcast.BroadcastDispatcher;
import com.android.systemui.colorextraction.SysuiColorExtractor;
import com.android.systemui.dock.DockManager;
import com.android.systemui.doze.MotoDisplayManager;
import com.android.systemui.dump.DumpManager;
import com.android.systemui.fragments.FragmentService;
import com.android.systemui.keyguard.ScreenLifecycle;
import com.android.systemui.keyguard.WakefulnessLifecycle;
import com.android.systemui.media.MediaCarouselController;
import com.android.systemui.media.dialog.MediaOutputDialogFactory;
import com.android.systemui.model.SysUiState;
import com.android.systemui.moto.DualSimIconController;
import com.android.systemui.navigationbar.NavigationBarController;
import com.android.systemui.navigationbar.NavigationBarOverlayController;
import com.android.systemui.navigationbar.NavigationModeController;
import com.android.systemui.navigationbar.gestural.EdgeBackGestureHandler;
import com.android.systemui.p006qs.QSTileHost;
import com.android.systemui.p006qs.ReduceBrightColorsController;
import com.android.systemui.p006qs.external.MotoDesktopProcessTileServices;
import com.android.systemui.plugins.ActivityStarter;
import com.android.systemui.plugins.DarkIconDispatcher;
import com.android.systemui.plugins.PluginDependencyProvider;
import com.android.systemui.plugins.VolumeDialogController;
import com.android.systemui.plugins.statusbar.StatusBarStateController;
import com.android.systemui.power.EnhancedEstimates;
import com.android.systemui.power.PowerUI;
import com.android.systemui.privacy.PrivacyItemController;
import com.android.systemui.recents.OverviewProxyService;
import com.android.systemui.recents.Recents;
import com.android.systemui.screenrecord.RecordingController;
import com.android.systemui.shared.plugins.PluginManager;
import com.android.systemui.shared.system.ActivityManagerWrapper;
import com.android.systemui.shared.system.DevicePolicyManagerWrapper;
import com.android.systemui.shared.system.PackageManagerWrapper;
import com.android.systemui.statusbar.CommandQueue;
import com.android.systemui.statusbar.FeatureFlags;
import com.android.systemui.statusbar.NotificationListener;
import com.android.systemui.statusbar.NotificationLockscreenUserManager;
import com.android.systemui.statusbar.NotificationMediaManager;
import com.android.systemui.statusbar.NotificationRemoteInputManager;
import com.android.systemui.statusbar.NotificationShadeWindowController;
import com.android.systemui.statusbar.NotificationViewHierarchyManager;
import com.android.systemui.statusbar.SmartReplyController;
import com.android.systemui.statusbar.VibratorHelper;
import com.android.systemui.statusbar.events.PrivacyDotViewController;
import com.android.systemui.statusbar.events.SystemStatusAnimationScheduler;
import com.android.systemui.statusbar.notification.NotificationEntryManager;
import com.android.systemui.statusbar.notification.NotificationFilter;
import com.android.systemui.statusbar.notification.collection.legacy.NotificationGroupManagerLegacy;
import com.android.systemui.statusbar.notification.collection.legacy.VisualStabilityManager;
import com.android.systemui.statusbar.notification.logging.NotificationLogger;
import com.android.systemui.statusbar.notification.row.NotificationGutsManager;
import com.android.systemui.statusbar.notification.stack.CliNotificationStackClient;
import com.android.systemui.statusbar.phone.AutoHideController;
import com.android.systemui.statusbar.phone.CliStatusBar;
import com.android.systemui.statusbar.phone.CliStatusBarWindowController;
import com.android.systemui.statusbar.phone.DozeParameters;
import com.android.systemui.statusbar.phone.KeyguardDismissUtil;
import com.android.systemui.statusbar.phone.LightBarController;
import com.android.systemui.statusbar.phone.LockscreenGestureLogger;
import com.android.systemui.statusbar.phone.ManagedProfileController;
import com.android.systemui.statusbar.phone.NotificationGroupAlertTransferHelper;
import com.android.systemui.statusbar.phone.ShadeController;
import com.android.systemui.statusbar.phone.StatusBar;
import com.android.systemui.statusbar.phone.StatusBarContentInsetsProvider;
import com.android.systemui.statusbar.phone.StatusBarIconController;
import com.android.systemui.statusbar.phone.StatusBarWindowController;
import com.android.systemui.statusbar.policy.AccessibilityController;
import com.android.systemui.statusbar.policy.AccessibilityManagerWrapper;
import com.android.systemui.statusbar.policy.BatteryController;
import com.android.systemui.statusbar.policy.BluetoothController;
import com.android.systemui.statusbar.policy.CastController;
import com.android.systemui.statusbar.policy.ConfigurationController;
import com.android.systemui.statusbar.policy.DataSaverController;
import com.android.systemui.statusbar.policy.DeviceProvisionedController;
import com.android.systemui.statusbar.policy.ExtensionController;
import com.android.systemui.statusbar.policy.FlashlightController;
import com.android.systemui.statusbar.policy.HotspotController;
import com.android.systemui.statusbar.policy.KeyguardStateController;
import com.android.systemui.statusbar.policy.LocationController;
import com.android.systemui.statusbar.policy.NetworkController;
import com.android.systemui.statusbar.policy.NextAlarmController;
import com.android.systemui.statusbar.policy.RemoteInputQuickSettingsDisabler;
import com.android.systemui.statusbar.policy.RotationLockController;
import com.android.systemui.statusbar.policy.SecurityController;
import com.android.systemui.statusbar.policy.SensorPrivacyController;
import com.android.systemui.statusbar.policy.SmartReplyConstants;
import com.android.systemui.statusbar.policy.UserInfoController;
import com.android.systemui.statusbar.policy.UserSwitcherController;
import com.android.systemui.statusbar.policy.ZenModeController;
import com.android.systemui.telephony.TelephonyListenerManager;
import com.android.systemui.tracing.ProtoTracer;
import com.android.systemui.tuner.TunablePadding;
import com.android.systemui.tuner.TunerService;
import com.android.systemui.util.DeviceConfigProxy;
import com.android.systemui.util.leak.GarbageMonitor;
import com.android.systemui.util.leak.LeakDetector;
import com.android.systemui.util.leak.LeakReporter;
import com.android.systemui.util.sensors.AsyncSensorManager;
import com.motorola.rro.RROsController;
import com.motorola.systemui.cli.navgesture.CliNavGestureController;
import com.motorola.systemui.cli.navgesture.MultiUserCliNavGestures;
import com.motorola.systemui.desktop.DesktopDisplayRootModulesManager;
import com.motorola.systemui.desktop.util.TooltipPopupManager;
import com.motorola.systemui.statusbar.policy.CellLocationController;
import com.motorola.systemui.statusbar.policy.NfcController;
import com.motorola.taskbar.MotoTaskBarController;
import dagger.Lazy;
import java.util.Objects;
import java.util.concurrent.Executor;
import java.util.function.Consumer;

public class Dependency {
    public static final DependencyKey<Executor> BACKGROUND_EXECUTOR = new DependencyKey<>("background_executor");
    public static final DependencyKey<Looper> BG_LOOPER = new DependencyKey<>("background_looper");
    public static final DependencyKey<String> LEAK_REPORT_EMAIL = new DependencyKey<>("leak_report_email");
    public static final DependencyKey<Executor> MAIN_EXECUTOR = new DependencyKey<>("main_executor");
    public static final DependencyKey<Handler> MAIN_HANDLER = new DependencyKey<>("main_handler");
    public static final DependencyKey<Looper> MAIN_LOOPER = new DependencyKey<>("main_looper");
    public static final DependencyKey<Handler> TIME_TICK_HANDLER = new DependencyKey<>("time_tick_handler");
    private static Dependency sDependency;
    Lazy<AccessibilityButtonTargetsObserver> mAccessibilityButtonListController;
    Lazy<AccessibilityButtonModeObserver> mAccessibilityButtonModeObserver;
    Lazy<AccessibilityController> mAccessibilityController;
    Lazy<AccessibilityFloatingMenuController> mAccessibilityFloatingMenuController;
    Lazy<AccessibilityManagerWrapper> mAccessibilityManagerWrapper;
    Lazy<ActivityManagerWrapper> mActivityManagerWrapper;
    Lazy<ActivityStarter> mActivityStarter;
    Lazy<AlarmManager> mAlarmManager;
    Lazy<AppOpsController> mAppOpsController;
    Lazy<AssistManager> mAssistManager;
    Lazy<AsyncSensorManager> mAsyncSensorManager;
    Lazy<AutoHideController> mAutoHideController;
    Lazy<Executor> mBackgroundExecutor;
    Lazy<BatteryController> mBatteryController;
    Lazy<Handler> mBgHandler;
    Lazy<Looper> mBgLooper;
    Lazy<BluetoothController> mBluetoothController;
    Lazy<BroadcastDispatcher> mBroadcastDispatcher;
    Lazy<CastController> mCastController;
    Lazy<CellLocationController> mCellLocationController;
    Lazy<CliNavGestureController> mCliNavGestureController;
    Lazy<CliNotificationStackClient> mCliNotificationStackClient;
    Lazy<CliStatusBar> mCliStatusBar;
    Lazy<CliStatusBarWindowController> mCliStatusBarWindowController;
    Lazy<ClockManager> mClockManager;
    Lazy<CommandQueue> mCommandQueue;
    Lazy<ConfigurationController> mConfigurationController;
    Lazy<StatusBarContentInsetsProvider> mContentInsetsProviderLazy;
    Lazy<DarkIconDispatcher> mDarkIconDispatcher;
    Lazy<DataSaverController> mDataSaverController;
    private final ArrayMap<Object, Object> mDependencies = new ArrayMap<>();
    Lazy<DesktopDisplayRootModulesManager> mDesktopDisplayRootModulesManager;
    Lazy<MotoDesktopProcessTileServices> mDesktopTileServices;
    Lazy<DeviceConfigProxy> mDeviceConfigProxy;
    Lazy<DevicePolicyManagerWrapper> mDevicePolicyManagerWrapper;
    Lazy<DeviceProvisionedController> mDeviceProvisionedController;
    Lazy<DisplayMetrics> mDisplayMetrics;
    Lazy<DockManager> mDockManager;
    Lazy<DozeParameters> mDozeParameters;
    Lazy<DualSimIconController> mDualSimIconController;
    DumpManager mDumpManager;
    Lazy<EdgeBackGestureHandler.Factory> mEdgeBackGestureHandlerFactoryLazy;
    Lazy<EnhancedEstimates> mEnhancedEstimates;
    Lazy<ExtensionController> mExtensionController;
    Lazy<FeatureFlags> mFeatureFlagsLazy;
    Lazy<FlashlightController> mFlashlightController;
    Lazy<ForegroundServiceController> mForegroundServiceController;
    Lazy<ForegroundServiceNotificationListener> mForegroundServiceNotificationListener;
    Lazy<FragmentService> mFragmentService;
    Lazy<GarbageMonitor> mGarbageMonitor;
    Lazy<HotspotController> mHotspotController;
    Lazy<INotificationManager> mINotificationManager;
    Lazy<IStatusBarService> mIStatusBarService;
    Lazy<IWindowManager> mIWindowManager;
    Lazy<KeyguardDismissUtil> mKeyguardDismissUtil;
    Lazy<NotificationEntryManager.KeyguardEnvironment> mKeyguardEnvironment;
    Lazy<KeyguardStateController> mKeyguardMonitor;
    Lazy<KeyguardSecurityModel> mKeyguardSecurityModel;
    Lazy<KeyguardUpdateMonitor> mKeyguardUpdateMonitor;
    Lazy<LeakDetector> mLeakDetector;
    Lazy<String> mLeakReportEmail;
    Lazy<LeakReporter> mLeakReporter;
    Lazy<LightBarController> mLightBarController;
    Lazy<LocalBluetoothManager> mLocalBluetoothManager;
    Lazy<LocationController> mLocationController;
    Lazy<LockscreenGestureLogger> mLockscreenGestureLogger;
    Lazy<Executor> mMainExecutor;
    Lazy<Handler> mMainHandler;
    Lazy<Looper> mMainLooper;
    Lazy<ManagedProfileController> mManagedProfileController;
    Lazy<MediaCarouselController> mMediaCarouselController;
    Lazy<MediaOutputDialogFactory> mMediaOutputDialogFactory;
    Lazy<MetricsLogger> mMetricsLogger;
    Lazy<MotoDisplayManager> mMotoDisplayManager;
    Lazy<MotoTaskBarController> mMotoTaskBarController;
    Lazy<MultiUserCliNavGestures> mMultiUserCliNavGestures;
    Lazy<NavigationModeController> mNavBarModeController;
    Lazy<NavigationBarOverlayController> mNavbarButtonsControllerLazy;
    Lazy<NavigationBarController> mNavigationBarController;
    Lazy<NetworkController> mNetworkController;
    Lazy<NextAlarmController> mNextAlarmController;
    Lazy<NfcController> mNfcController;
    Lazy<NightDisplayListener> mNightDisplayListener;
    Lazy<NotificationEntryManager> mNotificationEntryManager;
    Lazy<NotificationFilter> mNotificationFilter;
    Lazy<NotificationGroupAlertTransferHelper> mNotificationGroupAlertTransferHelper;
    Lazy<NotificationGroupManagerLegacy> mNotificationGroupManager;
    Lazy<NotificationGutsManager> mNotificationGutsManager;
    Lazy<NotificationListener> mNotificationListener;
    Lazy<NotificationLockscreenUserManager> mNotificationLockscreenUserManager;
    Lazy<NotificationLogger> mNotificationLogger;
    Lazy<NotificationMediaManager> mNotificationMediaManager;
    Lazy<NotificationRemoteInputManager> mNotificationRemoteInputManager;
    Lazy<NotificationRemoteInputManager.Callback> mNotificationRemoteInputManagerCallback;
    Lazy<NotificationShadeWindowController> mNotificationShadeWindowController;
    Lazy<NotificationViewHierarchyManager> mNotificationViewHierarchyManager;
    Lazy<OverviewProxyService> mOverviewProxyService;
    Lazy<PackageManagerWrapper> mPackageManagerWrapper;
    Lazy<PluginDependencyProvider> mPluginDependencyProvider;
    Lazy<PluginManager> mPluginManager;
    Lazy<PrivacyDotViewController> mPrivacyDotViewControllerLazy;
    Lazy<PrivacyItemController> mPrivacyItemController;
    Lazy<ProtoTracer> mProtoTracer;
    private final ArrayMap<Object, LazyDependencyCreator> mProviders = new ArrayMap<>();
    Lazy<QSTileHost> mQSTileHost;
    Lazy<RROsController> mRROsController;
    Lazy<Recents> mRecents;
    Lazy<RecordingController> mRecordingController;
    Lazy<ReduceBrightColorsController> mReduceBrightColorsController;
    Lazy<RemoteInputQuickSettingsDisabler> mRemoteInputQuickSettingsDisabler;
    Lazy<RotationLockController> mRotationLockController;
    Lazy<ScreenLifecycle> mScreenLifecycle;
    Lazy<SecurityController> mSecurityController;
    Lazy<SensorPrivacyController> mSensorPrivacyController;
    Lazy<SensorPrivacyManager> mSensorPrivacyManager;
    Lazy<ShadeController> mShadeController;
    Lazy<SmartReplyConstants> mSmartReplyConstants;
    Lazy<SmartReplyController> mSmartReplyController;
    Lazy<StatusBar> mStatusBar;
    Lazy<StatusBarIconController> mStatusBarIconController;
    Lazy<StatusBarStateController> mStatusBarStateController;
    Lazy<SysUiState> mSysUiStateFlagsContainer;
    Lazy<SystemStatusAnimationScheduler> mSystemStatusAnimationSchedulerLazy;
    Lazy<SysuiColorExtractor> mSysuiColorExtractor;
    Lazy<TelephonyListenerManager> mTelephonyListenerManager;
    Lazy<StatusBarWindowController> mTempStatusBarWindowController;
    Lazy<Handler> mTimeTickHandler;
    Lazy<TooltipPopupManager> mTooltipPopupManager;
    Lazy<TunablePadding.TunablePaddingService> mTunablePaddingService;
    Lazy<TunerService> mTunerService;
    Lazy<UiEventLogger> mUiEventLogger;
    Lazy<UiOffloadThread> mUiOffloadThread;
    Lazy<UserInfoController> mUserInfoController;
    Lazy<UserSwitcherController> mUserSwitcherController;
    Lazy<VibratorHelper> mVibratorHelper;
    Lazy<VisualStabilityManager> mVisualStabilityManager;
    Lazy<VolumeDialogController> mVolumeDialogController;
    Lazy<WakefulnessLifecycle> mWakefulnessLifecycle;
    Lazy<IWallpaperManager> mWallpaperManager;
    Lazy<PowerUI.WarningsUI> mWarningsUI;
    Lazy<ZenModeController> mZenModeController;

    private interface LazyDependencyCreator<T> {
        T createDependency();
    }

    /* access modifiers changed from: protected */
    @VisibleForTesting
    public boolean autoRegisterModulesForDump() {
        return true;
    }

    public void start() {
        ArrayMap<Object, LazyDependencyCreator> arrayMap = this.mProviders;
        DependencyKey<Handler> dependencyKey = TIME_TICK_HANDLER;
        Lazy<Handler> lazy = this.mTimeTickHandler;
        Objects.requireNonNull(lazy);
        arrayMap.put(dependencyKey, new Dependency$$ExternalSyntheticLambda0(lazy));
        ArrayMap<Object, LazyDependencyCreator> arrayMap2 = this.mProviders;
        DependencyKey<Looper> dependencyKey2 = BG_LOOPER;
        Lazy<Looper> lazy2 = this.mBgLooper;
        Objects.requireNonNull(lazy2);
        arrayMap2.put(dependencyKey2, new Dependency$$ExternalSyntheticLambda0(lazy2));
        ArrayMap<Object, LazyDependencyCreator> arrayMap3 = this.mProviders;
        DependencyKey<Looper> dependencyKey3 = MAIN_LOOPER;
        Lazy<Looper> lazy3 = this.mMainLooper;
        Objects.requireNonNull(lazy3);
        arrayMap3.put(dependencyKey3, new Dependency$$ExternalSyntheticLambda0(lazy3));
        ArrayMap<Object, LazyDependencyCreator> arrayMap4 = this.mProviders;
        DependencyKey<Handler> dependencyKey4 = MAIN_HANDLER;
        Lazy<Handler> lazy4 = this.mMainHandler;
        Objects.requireNonNull(lazy4);
        arrayMap4.put(dependencyKey4, new Dependency$$ExternalSyntheticLambda0(lazy4));
        ArrayMap<Object, LazyDependencyCreator> arrayMap5 = this.mProviders;
        DependencyKey<Executor> dependencyKey5 = MAIN_EXECUTOR;
        Lazy<Executor> lazy5 = this.mMainExecutor;
        Objects.requireNonNull(lazy5);
        arrayMap5.put(dependencyKey5, new Dependency$$ExternalSyntheticLambda0(lazy5));
        ArrayMap<Object, LazyDependencyCreator> arrayMap6 = this.mProviders;
        DependencyKey<Executor> dependencyKey6 = BACKGROUND_EXECUTOR;
        Lazy<Executor> lazy6 = this.mBackgroundExecutor;
        Objects.requireNonNull(lazy6);
        arrayMap6.put(dependencyKey6, new Dependency$$ExternalSyntheticLambda0(lazy6));
        Lazy<ActivityStarter> lazy7 = this.mActivityStarter;
        Objects.requireNonNull(lazy7);
        this.mProviders.put(ActivityStarter.class, new Dependency$$ExternalSyntheticLambda0(lazy7));
        Lazy<BroadcastDispatcher> lazy8 = this.mBroadcastDispatcher;
        Objects.requireNonNull(lazy8);
        this.mProviders.put(BroadcastDispatcher.class, new Dependency$$ExternalSyntheticLambda0(lazy8));
        Lazy<AsyncSensorManager> lazy9 = this.mAsyncSensorManager;
        Objects.requireNonNull(lazy9);
        this.mProviders.put(AsyncSensorManager.class, new Dependency$$ExternalSyntheticLambda0(lazy9));
        Lazy<BluetoothController> lazy10 = this.mBluetoothController;
        Objects.requireNonNull(lazy10);
        this.mProviders.put(BluetoothController.class, new Dependency$$ExternalSyntheticLambda0(lazy10));
        Lazy<SensorPrivacyManager> lazy11 = this.mSensorPrivacyManager;
        Objects.requireNonNull(lazy11);
        this.mProviders.put(SensorPrivacyManager.class, new Dependency$$ExternalSyntheticLambda0(lazy11));
        Lazy<LocationController> lazy12 = this.mLocationController;
        Objects.requireNonNull(lazy12);
        this.mProviders.put(LocationController.class, new Dependency$$ExternalSyntheticLambda0(lazy12));
        Lazy<RotationLockController> lazy13 = this.mRotationLockController;
        Objects.requireNonNull(lazy13);
        this.mProviders.put(RotationLockController.class, new Dependency$$ExternalSyntheticLambda0(lazy13));
        Lazy<NetworkController> lazy14 = this.mNetworkController;
        Objects.requireNonNull(lazy14);
        this.mProviders.put(NetworkController.class, new Dependency$$ExternalSyntheticLambda0(lazy14));
        Lazy<ZenModeController> lazy15 = this.mZenModeController;
        Objects.requireNonNull(lazy15);
        this.mProviders.put(ZenModeController.class, new Dependency$$ExternalSyntheticLambda0(lazy15));
        Lazy<HotspotController> lazy16 = this.mHotspotController;
        Objects.requireNonNull(lazy16);
        this.mProviders.put(HotspotController.class, new Dependency$$ExternalSyntheticLambda0(lazy16));
        Lazy<CastController> lazy17 = this.mCastController;
        Objects.requireNonNull(lazy17);
        this.mProviders.put(CastController.class, new Dependency$$ExternalSyntheticLambda0(lazy17));
        Lazy<FlashlightController> lazy18 = this.mFlashlightController;
        Objects.requireNonNull(lazy18);
        this.mProviders.put(FlashlightController.class, new Dependency$$ExternalSyntheticLambda0(lazy18));
        Lazy<KeyguardStateController> lazy19 = this.mKeyguardMonitor;
        Objects.requireNonNull(lazy19);
        this.mProviders.put(KeyguardStateController.class, new Dependency$$ExternalSyntheticLambda0(lazy19));
        Lazy<KeyguardUpdateMonitor> lazy20 = this.mKeyguardUpdateMonitor;
        Objects.requireNonNull(lazy20);
        this.mProviders.put(KeyguardUpdateMonitor.class, new Dependency$$ExternalSyntheticLambda0(lazy20));
        Lazy<UserSwitcherController> lazy21 = this.mUserSwitcherController;
        Objects.requireNonNull(lazy21);
        this.mProviders.put(UserSwitcherController.class, new Dependency$$ExternalSyntheticLambda0(lazy21));
        Lazy<UserInfoController> lazy22 = this.mUserInfoController;
        Objects.requireNonNull(lazy22);
        this.mProviders.put(UserInfoController.class, new Dependency$$ExternalSyntheticLambda0(lazy22));
        Lazy<BatteryController> lazy23 = this.mBatteryController;
        Objects.requireNonNull(lazy23);
        this.mProviders.put(BatteryController.class, new Dependency$$ExternalSyntheticLambda0(lazy23));
        Lazy<NightDisplayListener> lazy24 = this.mNightDisplayListener;
        Objects.requireNonNull(lazy24);
        this.mProviders.put(NightDisplayListener.class, new Dependency$$ExternalSyntheticLambda0(lazy24));
        Lazy<ReduceBrightColorsController> lazy25 = this.mReduceBrightColorsController;
        Objects.requireNonNull(lazy25);
        this.mProviders.put(ReduceBrightColorsController.class, new Dependency$$ExternalSyntheticLambda0(lazy25));
        Lazy<ManagedProfileController> lazy26 = this.mManagedProfileController;
        Objects.requireNonNull(lazy26);
        this.mProviders.put(ManagedProfileController.class, new Dependency$$ExternalSyntheticLambda0(lazy26));
        Lazy<NextAlarmController> lazy27 = this.mNextAlarmController;
        Objects.requireNonNull(lazy27);
        this.mProviders.put(NextAlarmController.class, new Dependency$$ExternalSyntheticLambda0(lazy27));
        Lazy<DataSaverController> lazy28 = this.mDataSaverController;
        Objects.requireNonNull(lazy28);
        this.mProviders.put(DataSaverController.class, new Dependency$$ExternalSyntheticLambda0(lazy28));
        Lazy<AccessibilityController> lazy29 = this.mAccessibilityController;
        Objects.requireNonNull(lazy29);
        this.mProviders.put(AccessibilityController.class, new Dependency$$ExternalSyntheticLambda0(lazy29));
        Lazy<DeviceProvisionedController> lazy30 = this.mDeviceProvisionedController;
        Objects.requireNonNull(lazy30);
        this.mProviders.put(DeviceProvisionedController.class, new Dependency$$ExternalSyntheticLambda0(lazy30));
        Lazy<PluginManager> lazy31 = this.mPluginManager;
        Objects.requireNonNull(lazy31);
        this.mProviders.put(PluginManager.class, new Dependency$$ExternalSyntheticLambda0(lazy31));
        Lazy<AssistManager> lazy32 = this.mAssistManager;
        Objects.requireNonNull(lazy32);
        this.mProviders.put(AssistManager.class, new Dependency$$ExternalSyntheticLambda0(lazy32));
        Lazy<SecurityController> lazy33 = this.mSecurityController;
        Objects.requireNonNull(lazy33);
        this.mProviders.put(SecurityController.class, new Dependency$$ExternalSyntheticLambda0(lazy33));
        Lazy<LeakDetector> lazy34 = this.mLeakDetector;
        Objects.requireNonNull(lazy34);
        this.mProviders.put(LeakDetector.class, new Dependency$$ExternalSyntheticLambda0(lazy34));
        ArrayMap<Object, LazyDependencyCreator> arrayMap7 = this.mProviders;
        DependencyKey<String> dependencyKey7 = LEAK_REPORT_EMAIL;
        Lazy<String> lazy35 = this.mLeakReportEmail;
        Objects.requireNonNull(lazy35);
        arrayMap7.put(dependencyKey7, new Dependency$$ExternalSyntheticLambda0(lazy35));
        Lazy<LeakReporter> lazy36 = this.mLeakReporter;
        Objects.requireNonNull(lazy36);
        this.mProviders.put(LeakReporter.class, new Dependency$$ExternalSyntheticLambda0(lazy36));
        Lazy<GarbageMonitor> lazy37 = this.mGarbageMonitor;
        Objects.requireNonNull(lazy37);
        this.mProviders.put(GarbageMonitor.class, new Dependency$$ExternalSyntheticLambda0(lazy37));
        Lazy<TunerService> lazy38 = this.mTunerService;
        Objects.requireNonNull(lazy38);
        this.mProviders.put(TunerService.class, new Dependency$$ExternalSyntheticLambda0(lazy38));
        Lazy<NotificationShadeWindowController> lazy39 = this.mNotificationShadeWindowController;
        Objects.requireNonNull(lazy39);
        this.mProviders.put(NotificationShadeWindowController.class, new Dependency$$ExternalSyntheticLambda0(lazy39));
        Lazy<StatusBarWindowController> lazy40 = this.mTempStatusBarWindowController;
        Objects.requireNonNull(lazy40);
        this.mProviders.put(StatusBarWindowController.class, new Dependency$$ExternalSyntheticLambda0(lazy40));
        Lazy<CliStatusBarWindowController> lazy41 = this.mCliStatusBarWindowController;
        Objects.requireNonNull(lazy41);
        this.mProviders.put(CliStatusBarWindowController.class, new Dependency$$ExternalSyntheticLambda0(lazy41));
        Lazy<DarkIconDispatcher> lazy42 = this.mDarkIconDispatcher;
        Objects.requireNonNull(lazy42);
        this.mProviders.put(DarkIconDispatcher.class, new Dependency$$ExternalSyntheticLambda0(lazy42));
        Lazy<ConfigurationController> lazy43 = this.mConfigurationController;
        Objects.requireNonNull(lazy43);
        this.mProviders.put(ConfigurationController.class, new Dependency$$ExternalSyntheticLambda0(lazy43));
        Lazy<StatusBarIconController> lazy44 = this.mStatusBarIconController;
        Objects.requireNonNull(lazy44);
        this.mProviders.put(StatusBarIconController.class, new Dependency$$ExternalSyntheticLambda0(lazy44));
        Lazy<ScreenLifecycle> lazy45 = this.mScreenLifecycle;
        Objects.requireNonNull(lazy45);
        this.mProviders.put(ScreenLifecycle.class, new Dependency$$ExternalSyntheticLambda0(lazy45));
        Lazy<WakefulnessLifecycle> lazy46 = this.mWakefulnessLifecycle;
        Objects.requireNonNull(lazy46);
        this.mProviders.put(WakefulnessLifecycle.class, new Dependency$$ExternalSyntheticLambda0(lazy46));
        Lazy<FragmentService> lazy47 = this.mFragmentService;
        Objects.requireNonNull(lazy47);
        this.mProviders.put(FragmentService.class, new Dependency$$ExternalSyntheticLambda0(lazy47));
        Lazy<ExtensionController> lazy48 = this.mExtensionController;
        Objects.requireNonNull(lazy48);
        this.mProviders.put(ExtensionController.class, new Dependency$$ExternalSyntheticLambda0(lazy48));
        Lazy<PluginDependencyProvider> lazy49 = this.mPluginDependencyProvider;
        Objects.requireNonNull(lazy49);
        this.mProviders.put(PluginDependencyProvider.class, new Dependency$$ExternalSyntheticLambda0(lazy49));
        Lazy<LocalBluetoothManager> lazy50 = this.mLocalBluetoothManager;
        Objects.requireNonNull(lazy50);
        this.mProviders.put(LocalBluetoothManager.class, new Dependency$$ExternalSyntheticLambda0(lazy50));
        Lazy<VolumeDialogController> lazy51 = this.mVolumeDialogController;
        Objects.requireNonNull(lazy51);
        this.mProviders.put(VolumeDialogController.class, new Dependency$$ExternalSyntheticLambda0(lazy51));
        Lazy<MetricsLogger> lazy52 = this.mMetricsLogger;
        Objects.requireNonNull(lazy52);
        this.mProviders.put(MetricsLogger.class, new Dependency$$ExternalSyntheticLambda0(lazy52));
        Lazy<AccessibilityManagerWrapper> lazy53 = this.mAccessibilityManagerWrapper;
        Objects.requireNonNull(lazy53);
        this.mProviders.put(AccessibilityManagerWrapper.class, new Dependency$$ExternalSyntheticLambda0(lazy53));
        Lazy<SysuiColorExtractor> lazy54 = this.mSysuiColorExtractor;
        Objects.requireNonNull(lazy54);
        this.mProviders.put(SysuiColorExtractor.class, new Dependency$$ExternalSyntheticLambda0(lazy54));
        Lazy<TunablePadding.TunablePaddingService> lazy55 = this.mTunablePaddingService;
        Objects.requireNonNull(lazy55);
        this.mProviders.put(TunablePadding.TunablePaddingService.class, new Dependency$$ExternalSyntheticLambda0(lazy55));
        Lazy<ForegroundServiceController> lazy56 = this.mForegroundServiceController;
        Objects.requireNonNull(lazy56);
        this.mProviders.put(ForegroundServiceController.class, new Dependency$$ExternalSyntheticLambda0(lazy56));
        Lazy<UiOffloadThread> lazy57 = this.mUiOffloadThread;
        Objects.requireNonNull(lazy57);
        this.mProviders.put(UiOffloadThread.class, new Dependency$$ExternalSyntheticLambda0(lazy57));
        Lazy<PowerUI.WarningsUI> lazy58 = this.mWarningsUI;
        Objects.requireNonNull(lazy58);
        this.mProviders.put(PowerUI.WarningsUI.class, new Dependency$$ExternalSyntheticLambda0(lazy58));
        Lazy<LightBarController> lazy59 = this.mLightBarController;
        Objects.requireNonNull(lazy59);
        this.mProviders.put(LightBarController.class, new Dependency$$ExternalSyntheticLambda0(lazy59));
        Lazy<IWindowManager> lazy60 = this.mIWindowManager;
        Objects.requireNonNull(lazy60);
        this.mProviders.put(IWindowManager.class, new Dependency$$ExternalSyntheticLambda0(lazy60));
        Lazy<OverviewProxyService> lazy61 = this.mOverviewProxyService;
        Objects.requireNonNull(lazy61);
        this.mProviders.put(OverviewProxyService.class, new Dependency$$ExternalSyntheticLambda0(lazy61));
        Lazy<CliNotificationStackClient> lazy62 = this.mCliNotificationStackClient;
        Objects.requireNonNull(lazy62);
        this.mProviders.put(CliNotificationStackClient.class, new Dependency$$ExternalSyntheticLambda0(lazy62));
        Lazy<NavigationModeController> lazy63 = this.mNavBarModeController;
        Objects.requireNonNull(lazy63);
        this.mProviders.put(NavigationModeController.class, new Dependency$$ExternalSyntheticLambda0(lazy63));
        Lazy<AccessibilityButtonModeObserver> lazy64 = this.mAccessibilityButtonModeObserver;
        Objects.requireNonNull(lazy64);
        this.mProviders.put(AccessibilityButtonModeObserver.class, new Dependency$$ExternalSyntheticLambda0(lazy64));
        Lazy<AccessibilityButtonTargetsObserver> lazy65 = this.mAccessibilityButtonListController;
        Objects.requireNonNull(lazy65);
        this.mProviders.put(AccessibilityButtonTargetsObserver.class, new Dependency$$ExternalSyntheticLambda0(lazy65));
        Lazy<EnhancedEstimates> lazy66 = this.mEnhancedEstimates;
        Objects.requireNonNull(lazy66);
        this.mProviders.put(EnhancedEstimates.class, new Dependency$$ExternalSyntheticLambda0(lazy66));
        Lazy<VibratorHelper> lazy67 = this.mVibratorHelper;
        Objects.requireNonNull(lazy67);
        this.mProviders.put(VibratorHelper.class, new Dependency$$ExternalSyntheticLambda0(lazy67));
        Lazy<IStatusBarService> lazy68 = this.mIStatusBarService;
        Objects.requireNonNull(lazy68);
        this.mProviders.put(IStatusBarService.class, new Dependency$$ExternalSyntheticLambda0(lazy68));
        Lazy<DisplayMetrics> lazy69 = this.mDisplayMetrics;
        Objects.requireNonNull(lazy69);
        this.mProviders.put(DisplayMetrics.class, new Dependency$$ExternalSyntheticLambda0(lazy69));
        Lazy<LockscreenGestureLogger> lazy70 = this.mLockscreenGestureLogger;
        Objects.requireNonNull(lazy70);
        this.mProviders.put(LockscreenGestureLogger.class, new Dependency$$ExternalSyntheticLambda0(lazy70));
        Lazy<NotificationEntryManager.KeyguardEnvironment> lazy71 = this.mKeyguardEnvironment;
        Objects.requireNonNull(lazy71);
        this.mProviders.put(NotificationEntryManager.KeyguardEnvironment.class, new Dependency$$ExternalSyntheticLambda0(lazy71));
        Lazy<ShadeController> lazy72 = this.mShadeController;
        Objects.requireNonNull(lazy72);
        this.mProviders.put(ShadeController.class, new Dependency$$ExternalSyntheticLambda0(lazy72));
        Lazy<NotificationRemoteInputManager.Callback> lazy73 = this.mNotificationRemoteInputManagerCallback;
        Objects.requireNonNull(lazy73);
        this.mProviders.put(NotificationRemoteInputManager.Callback.class, new Dependency$$ExternalSyntheticLambda0(lazy73));
        Lazy<AppOpsController> lazy74 = this.mAppOpsController;
        Objects.requireNonNull(lazy74);
        this.mProviders.put(AppOpsController.class, new Dependency$$ExternalSyntheticLambda0(lazy74));
        Lazy<NavigationBarController> lazy75 = this.mNavigationBarController;
        Objects.requireNonNull(lazy75);
        this.mProviders.put(NavigationBarController.class, new Dependency$$ExternalSyntheticLambda0(lazy75));
        Lazy<AccessibilityFloatingMenuController> lazy76 = this.mAccessibilityFloatingMenuController;
        Objects.requireNonNull(lazy76);
        this.mProviders.put(AccessibilityFloatingMenuController.class, new Dependency$$ExternalSyntheticLambda0(lazy76));
        Lazy<StatusBarStateController> lazy77 = this.mStatusBarStateController;
        Objects.requireNonNull(lazy77);
        this.mProviders.put(StatusBarStateController.class, new Dependency$$ExternalSyntheticLambda0(lazy77));
        Lazy<NotificationLockscreenUserManager> lazy78 = this.mNotificationLockscreenUserManager;
        Objects.requireNonNull(lazy78);
        this.mProviders.put(NotificationLockscreenUserManager.class, new Dependency$$ExternalSyntheticLambda0(lazy78));
        Lazy<VisualStabilityManager> lazy79 = this.mVisualStabilityManager;
        Objects.requireNonNull(lazy79);
        this.mProviders.put(VisualStabilityManager.class, new Dependency$$ExternalSyntheticLambda0(lazy79));
        Lazy<NotificationGroupManagerLegacy> lazy80 = this.mNotificationGroupManager;
        Objects.requireNonNull(lazy80);
        this.mProviders.put(NotificationGroupManagerLegacy.class, new Dependency$$ExternalSyntheticLambda0(lazy80));
        Lazy<NotificationGroupAlertTransferHelper> lazy81 = this.mNotificationGroupAlertTransferHelper;
        Objects.requireNonNull(lazy81);
        this.mProviders.put(NotificationGroupAlertTransferHelper.class, new Dependency$$ExternalSyntheticLambda0(lazy81));
        Lazy<NotificationMediaManager> lazy82 = this.mNotificationMediaManager;
        Objects.requireNonNull(lazy82);
        this.mProviders.put(NotificationMediaManager.class, new Dependency$$ExternalSyntheticLambda0(lazy82));
        Lazy<NotificationGutsManager> lazy83 = this.mNotificationGutsManager;
        Objects.requireNonNull(lazy83);
        this.mProviders.put(NotificationGutsManager.class, new Dependency$$ExternalSyntheticLambda0(lazy83));
        Lazy<NotificationRemoteInputManager> lazy84 = this.mNotificationRemoteInputManager;
        Objects.requireNonNull(lazy84);
        this.mProviders.put(NotificationRemoteInputManager.class, new Dependency$$ExternalSyntheticLambda0(lazy84));
        Lazy<SmartReplyConstants> lazy85 = this.mSmartReplyConstants;
        Objects.requireNonNull(lazy85);
        this.mProviders.put(SmartReplyConstants.class, new Dependency$$ExternalSyntheticLambda0(lazy85));
        Lazy<NotificationListener> lazy86 = this.mNotificationListener;
        Objects.requireNonNull(lazy86);
        this.mProviders.put(NotificationListener.class, new Dependency$$ExternalSyntheticLambda0(lazy86));
        Lazy<NotificationLogger> lazy87 = this.mNotificationLogger;
        Objects.requireNonNull(lazy87);
        this.mProviders.put(NotificationLogger.class, new Dependency$$ExternalSyntheticLambda0(lazy87));
        Lazy<NotificationViewHierarchyManager> lazy88 = this.mNotificationViewHierarchyManager;
        Objects.requireNonNull(lazy88);
        this.mProviders.put(NotificationViewHierarchyManager.class, new Dependency$$ExternalSyntheticLambda0(lazy88));
        Lazy<NotificationFilter> lazy89 = this.mNotificationFilter;
        Objects.requireNonNull(lazy89);
        this.mProviders.put(NotificationFilter.class, new Dependency$$ExternalSyntheticLambda0(lazy89));
        Lazy<KeyguardDismissUtil> lazy90 = this.mKeyguardDismissUtil;
        Objects.requireNonNull(lazy90);
        this.mProviders.put(KeyguardDismissUtil.class, new Dependency$$ExternalSyntheticLambda0(lazy90));
        Lazy<SmartReplyController> lazy91 = this.mSmartReplyController;
        Objects.requireNonNull(lazy91);
        this.mProviders.put(SmartReplyController.class, new Dependency$$ExternalSyntheticLambda0(lazy91));
        Lazy<RemoteInputQuickSettingsDisabler> lazy92 = this.mRemoteInputQuickSettingsDisabler;
        Objects.requireNonNull(lazy92);
        this.mProviders.put(RemoteInputQuickSettingsDisabler.class, new Dependency$$ExternalSyntheticLambda0(lazy92));
        Lazy<NotificationEntryManager> lazy93 = this.mNotificationEntryManager;
        Objects.requireNonNull(lazy93);
        this.mProviders.put(NotificationEntryManager.class, new Dependency$$ExternalSyntheticLambda0(lazy93));
        Lazy<ForegroundServiceNotificationListener> lazy94 = this.mForegroundServiceNotificationListener;
        Objects.requireNonNull(lazy94);
        this.mProviders.put(ForegroundServiceNotificationListener.class, new Dependency$$ExternalSyntheticLambda0(lazy94));
        Lazy<ClockManager> lazy95 = this.mClockManager;
        Objects.requireNonNull(lazy95);
        this.mProviders.put(ClockManager.class, new Dependency$$ExternalSyntheticLambda0(lazy95));
        Lazy<PrivacyItemController> lazy96 = this.mPrivacyItemController;
        Objects.requireNonNull(lazy96);
        this.mProviders.put(PrivacyItemController.class, new Dependency$$ExternalSyntheticLambda0(lazy96));
        Lazy<ActivityManagerWrapper> lazy97 = this.mActivityManagerWrapper;
        Objects.requireNonNull(lazy97);
        this.mProviders.put(ActivityManagerWrapper.class, new Dependency$$ExternalSyntheticLambda0(lazy97));
        Lazy<DevicePolicyManagerWrapper> lazy98 = this.mDevicePolicyManagerWrapper;
        Objects.requireNonNull(lazy98);
        this.mProviders.put(DevicePolicyManagerWrapper.class, new Dependency$$ExternalSyntheticLambda0(lazy98));
        Lazy<PackageManagerWrapper> lazy99 = this.mPackageManagerWrapper;
        Objects.requireNonNull(lazy99);
        this.mProviders.put(PackageManagerWrapper.class, new Dependency$$ExternalSyntheticLambda0(lazy99));
        Lazy<SensorPrivacyController> lazy100 = this.mSensorPrivacyController;
        Objects.requireNonNull(lazy100);
        this.mProviders.put(SensorPrivacyController.class, new Dependency$$ExternalSyntheticLambda0(lazy100));
        Lazy<DockManager> lazy101 = this.mDockManager;
        Objects.requireNonNull(lazy101);
        this.mProviders.put(DockManager.class, new Dependency$$ExternalSyntheticLambda0(lazy101));
        Lazy<INotificationManager> lazy102 = this.mINotificationManager;
        Objects.requireNonNull(lazy102);
        this.mProviders.put(INotificationManager.class, new Dependency$$ExternalSyntheticLambda0(lazy102));
        Lazy<SysUiState> lazy103 = this.mSysUiStateFlagsContainer;
        Objects.requireNonNull(lazy103);
        this.mProviders.put(SysUiState.class, new Dependency$$ExternalSyntheticLambda0(lazy103));
        Lazy<AlarmManager> lazy104 = this.mAlarmManager;
        Objects.requireNonNull(lazy104);
        this.mProviders.put(AlarmManager.class, new Dependency$$ExternalSyntheticLambda0(lazy104));
        Lazy<KeyguardSecurityModel> lazy105 = this.mKeyguardSecurityModel;
        Objects.requireNonNull(lazy105);
        this.mProviders.put(KeyguardSecurityModel.class, new Dependency$$ExternalSyntheticLambda0(lazy105));
        Lazy<DozeParameters> lazy106 = this.mDozeParameters;
        Objects.requireNonNull(lazy106);
        this.mProviders.put(DozeParameters.class, new Dependency$$ExternalSyntheticLambda0(lazy106));
        Lazy<IWallpaperManager> lazy107 = this.mWallpaperManager;
        Objects.requireNonNull(lazy107);
        this.mProviders.put(IWallpaperManager.class, new Dependency$$ExternalSyntheticLambda0(lazy107));
        Lazy<CommandQueue> lazy108 = this.mCommandQueue;
        Objects.requireNonNull(lazy108);
        this.mProviders.put(CommandQueue.class, new Dependency$$ExternalSyntheticLambda0(lazy108));
        Lazy<Recents> lazy109 = this.mRecents;
        Objects.requireNonNull(lazy109);
        this.mProviders.put(Recents.class, new Dependency$$ExternalSyntheticLambda0(lazy109));
        Lazy<StatusBar> lazy110 = this.mStatusBar;
        Objects.requireNonNull(lazy110);
        this.mProviders.put(StatusBar.class, new Dependency$$ExternalSyntheticLambda0(lazy110));
        Lazy<CliStatusBar> lazy111 = this.mCliStatusBar;
        Objects.requireNonNull(lazy111);
        this.mProviders.put(CliStatusBar.class, new Dependency$$ExternalSyntheticLambda0(lazy111));
        Lazy<ProtoTracer> lazy112 = this.mProtoTracer;
        Objects.requireNonNull(lazy112);
        this.mProviders.put(ProtoTracer.class, new Dependency$$ExternalSyntheticLambda0(lazy112));
        Lazy<DeviceConfigProxy> lazy113 = this.mDeviceConfigProxy;
        Objects.requireNonNull(lazy113);
        this.mProviders.put(DeviceConfigProxy.class, new Dependency$$ExternalSyntheticLambda0(lazy113));
        Lazy<TelephonyListenerManager> lazy114 = this.mTelephonyListenerManager;
        Objects.requireNonNull(lazy114);
        this.mProviders.put(TelephonyListenerManager.class, new Dependency$$ExternalSyntheticLambda0(lazy114));
        Lazy<AutoHideController> lazy115 = this.mAutoHideController;
        Objects.requireNonNull(lazy115);
        this.mProviders.put(AutoHideController.class, new Dependency$$ExternalSyntheticLambda0(lazy115));
        Lazy<RecordingController> lazy116 = this.mRecordingController;
        Objects.requireNonNull(lazy116);
        this.mProviders.put(RecordingController.class, new Dependency$$ExternalSyntheticLambda0(lazy116));
        Lazy<NfcController> lazy117 = this.mNfcController;
        Objects.requireNonNull(lazy117);
        this.mProviders.put(NfcController.class, new Dependency$$ExternalSyntheticLambda0(lazy117));
        Lazy<MotoTaskBarController> lazy118 = this.mMotoTaskBarController;
        Objects.requireNonNull(lazy118);
        this.mProviders.put(MotoTaskBarController.class, new Dependency$$ExternalSyntheticLambda0(lazy118));
        Lazy<CellLocationController> lazy119 = this.mCellLocationController;
        Objects.requireNonNull(lazy119);
        this.mProviders.put(CellLocationController.class, new Dependency$$ExternalSyntheticLambda0(lazy119));
        Lazy<CliNavGestureController> lazy120 = this.mCliNavGestureController;
        Objects.requireNonNull(lazy120);
        this.mProviders.put(CliNavGestureController.class, new Dependency$$ExternalSyntheticLambda0(lazy120));
        Lazy<MultiUserCliNavGestures> lazy121 = this.mMultiUserCliNavGestures;
        Objects.requireNonNull(lazy121);
        this.mProviders.put(MultiUserCliNavGestures.class, new Dependency$$ExternalSyntheticLambda0(lazy121));
        Lazy<MediaOutputDialogFactory> lazy122 = this.mMediaOutputDialogFactory;
        Objects.requireNonNull(lazy122);
        this.mProviders.put(MediaOutputDialogFactory.class, new Dependency$$ExternalSyntheticLambda0(lazy122));
        Lazy<NavigationBarOverlayController> lazy123 = this.mNavbarButtonsControllerLazy;
        Objects.requireNonNull(lazy123);
        this.mProviders.put(NavigationBarOverlayController.class, new Dependency$$ExternalSyntheticLambda0(lazy123));
        Lazy<SystemStatusAnimationScheduler> lazy124 = this.mSystemStatusAnimationSchedulerLazy;
        Objects.requireNonNull(lazy124);
        this.mProviders.put(SystemStatusAnimationScheduler.class, new Dependency$$ExternalSyntheticLambda0(lazy124));
        Lazy<PrivacyDotViewController> lazy125 = this.mPrivacyDotViewControllerLazy;
        Objects.requireNonNull(lazy125);
        this.mProviders.put(PrivacyDotViewController.class, new Dependency$$ExternalSyntheticLambda0(lazy125));
        Lazy<EdgeBackGestureHandler.Factory> lazy126 = this.mEdgeBackGestureHandlerFactoryLazy;
        Objects.requireNonNull(lazy126);
        this.mProviders.put(EdgeBackGestureHandler.Factory.class, new Dependency$$ExternalSyntheticLambda0(lazy126));
        Lazy<UiEventLogger> lazy127 = this.mUiEventLogger;
        Objects.requireNonNull(lazy127);
        this.mProviders.put(UiEventLogger.class, new Dependency$$ExternalSyntheticLambda0(lazy127));
        Lazy<FeatureFlags> lazy128 = this.mFeatureFlagsLazy;
        Objects.requireNonNull(lazy128);
        this.mProviders.put(FeatureFlags.class, new Dependency$$ExternalSyntheticLambda0(lazy128));
        Lazy<StatusBarContentInsetsProvider> lazy129 = this.mContentInsetsProviderLazy;
        Objects.requireNonNull(lazy129);
        this.mProviders.put(StatusBarContentInsetsProvider.class, new Dependency$$ExternalSyntheticLambda0(lazy129));
        Lazy<DualSimIconController> lazy130 = this.mDualSimIconController;
        Objects.requireNonNull(lazy130);
        this.mProviders.put(DualSimIconController.class, new Dependency$$ExternalSyntheticLambda0(lazy130));
        Lazy<RROsController> lazy131 = this.mRROsController;
        Objects.requireNonNull(lazy131);
        this.mProviders.put(RROsController.class, new Dependency$$ExternalSyntheticLambda0(lazy131));
        Lazy<MotoDisplayManager> lazy132 = this.mMotoDisplayManager;
        Objects.requireNonNull(lazy132);
        this.mProviders.put(MotoDisplayManager.class, new Dependency$$ExternalSyntheticLambda0(lazy132));
        Lazy<MediaCarouselController> lazy133 = this.mMediaCarouselController;
        Objects.requireNonNull(lazy133);
        this.mProviders.put(MediaCarouselController.class, new Dependency$$ExternalSyntheticLambda0(lazy133));
        Lazy<TooltipPopupManager> lazy134 = this.mTooltipPopupManager;
        Objects.requireNonNull(lazy134);
        this.mProviders.put(TooltipPopupManager.class, new Dependency$$ExternalSyntheticLambda0(lazy134));
        Lazy<MotoDesktopProcessTileServices> lazy135 = this.mDesktopTileServices;
        Objects.requireNonNull(lazy135);
        this.mProviders.put(MotoDesktopProcessTileServices.class, new Dependency$$ExternalSyntheticLambda0(lazy135));
        Lazy<DesktopDisplayRootModulesManager> lazy136 = this.mDesktopDisplayRootModulesManager;
        Objects.requireNonNull(lazy136);
        this.mProviders.put(DesktopDisplayRootModulesManager.class, new Dependency$$ExternalSyntheticLambda0(lazy136));
        Lazy<QSTileHost> lazy137 = this.mQSTileHost;
        Objects.requireNonNull(lazy137);
        this.mProviders.put(QSTileHost.class, new Dependency$$ExternalSyntheticLambda0(lazy137));
        setInstance(this);
    }

    @VisibleForTesting
    public static void setInstance(Dependency dependency) {
        sDependency = dependency;
    }

    /* access modifiers changed from: protected */
    public final <T> T getDependency(Class<T> cls) {
        return getDependencyInner(cls);
    }

    /* access modifiers changed from: protected */
    public final <T> T getDependency(DependencyKey<T> dependencyKey) {
        return getDependencyInner(dependencyKey);
    }

    private synchronized <T> T getDependencyInner(Object obj) {
        T t;
        t = this.mDependencies.get(obj);
        if (t == null) {
            t = createDependency(obj);
            this.mDependencies.put(obj, t);
            if (autoRegisterModulesForDump() && (t instanceof Dumpable)) {
                this.mDumpManager.registerDumpable(t.getClass().getName(), (Dumpable) t);
            }
        }
        return t;
    }

    @VisibleForTesting
    public <T> T createDependency(Object obj) {
        Preconditions.checkArgument((obj instanceof DependencyKey) || (obj instanceof Class));
        LazyDependencyCreator lazyDependencyCreator = this.mProviders.get(obj);
        if (lazyDependencyCreator != null) {
            return lazyDependencyCreator.createDependency();
        }
        throw new IllegalArgumentException("Unsupported dependency " + obj + ". " + this.mProviders.size() + " providers known.");
    }

    private <T> void destroyDependency(Class<T> cls, Consumer<T> consumer) {
        Object remove = this.mDependencies.remove(cls);
        if (remove instanceof Dumpable) {
            this.mDumpManager.unregisterDumpable(remove.getClass().getName());
        }
        if (remove != null && consumer != null) {
            consumer.accept(remove);
        }
    }

    public static <T> void destroy(Class<T> cls, Consumer<T> consumer) {
        sDependency.destroyDependency(cls, consumer);
    }

    @Deprecated
    public static <T> T get(Class<T> cls) {
        return sDependency.getDependency(cls);
    }

    @Deprecated
    public static <T> T get(DependencyKey<T> dependencyKey) {
        return sDependency.getDependency(dependencyKey);
    }

    public static final class DependencyKey<V> {
        private final String mDisplayName;

        public DependencyKey(String str) {
            this.mDisplayName = str;
        }

        public String toString() {
            return this.mDisplayName;
        }
    }
}
